// export const tags = [
// 	{ label: "python", value: "python" },
// 	{ label: "javascript", value: "javascript" },
// 	{ label: "html", value: "html" },
// 	{ label: "css", value: "css" },
// 	{ label: "react", value: "react" },
// 	{ label: "angular", value: "angular" },
// 	{ label: "node.js", value: "node.js" },
// 	{ label: "express.js", value: "express.js" },
// 	{ label: "typescript", value: "typescript" },
// 	{ label: "vue.js", value: "vue.js" },
// 	{ label: "redux", value: "redux" },
// 	{ label: "graphql", value: "graphql" },
// 	{ label: "docker", value: "docker" },
// 	{ label: "kubernetes", value: "kubernetes" },
// 	{ label: "aws", value: "aws" },
// 	{ label: "azure", value: "azure" },
// 	{ label: "gcp", value: "gcp" },
// 	{ label: "git", value: "git" },
// 	{ label: "jenkins", value: "jenkins" },
// 	{ label: "mongodb", value: "mongodb" },
// 	{ label: "mysql", value: "mysql" },
// 	{ label: "postgresql", value: "postgresql" },
// 	{ label: "firebase", value: "firebase" },
// 	{ label: "machine learning", value: "machine learning" },
// 	{ label: "artificial intelligence", value: "artificial intelligence" },
// 	{ label: "big data", value: "big data" },
// 	{ label: "cybersecurity", value: "cybersecurity" },
// 	{ label: "blockchain", value: "blockchain" },
// 	{ label: "api", value: "api" },
// 	{ label: "microservices", value: "microservices" },
// 	{ label: "agile", value: "agile" },
// 	{ label: "devops", value: "devops" },
// 	{ label: "mobile development", value: "mobile development" },
// 	{ label: "web development", value: "web development" },
// 	{ label: "serverless", value: "serverless" },
// 	{ label: "linux", value: "linux" },
// 	{ label: "windows", value: "windows" },
// 	{ label: "macos", value: "macos" },
// 	{ label: "ios", value: "ios" },
// 	{ label: "android", value: "android" },
// 	{ label: "iot", value: "iot" },
// 	{ label: "data science", value: "data science" },
// 	{ label: "cloud computing", value: "cloud computing" },
// 	{ label: "frontend", value: "frontend" },
// 	{ label: "backend", value: "backend" },
// 	{ label: "full stack", value: "full stack" },
// ];

export const categories = [
	{ label: "technology", value: "technology" },
	{ label: "travel", value: "travel" },
	{ label: "food and recipe", value: "food and recipe" },
	{ label: "personal development", value: "personal development" },
	{ label: "lifestyle", value: "lifestyle" },
	{ label: "fashion and beauty", value: "fashion and beauty" },
	{
		label: "entertainment",
		value: "entertainment",
	},
	{ label: "sport", value: "sport" },
	{ label: "politics", value: "politics" },
	{ label: "relationship", value: "relationship" },
	{ label: "how to guide", value: "how to guide" },
];

export const tags = [
	{
		label: "Artificial Intelligence",
		value: "artificial-intelligence",
		category: "technology",
	},
	{
		label: "Software Development",
		value: "software-development",
		category: "technology",
	},
	{ label: "Cybersecurity", value: "cybersecurity", category: "technology" },
	{
		label: "Web Development",
		value: "web-development",
		category: "technology",
	},
	{ label: "Hardware", value: "hardware", category: "technology" },
	{ label: "Robotics", value: "robotics", category: "technology" },
	{ label: "gadgets", value: "gadgets", category: "technology" },
	{ label: "Adventure Travel", value: "adventure-travel", category: "travel" },
	{ label: "Backpacking", value: "backpacking", category: "travel" },
	{ label: "Luxury Travel", value: "luxury-travel", category: "travel" },
	{ label: "Food & Culture", value: "food-and-culture", category: "travel" },
	{ label: "Budget Travel", value: "budget-travel", category: "travel" },

	{
		label: "World Cuisine",
		value: "world-cuisine",
		category: "food and recipe",
	},
	{
		label: "Healthy Eating",
		value: "healthy-eating",
		category: "food and recipe",
	},
	{ label: "Baking", value: "baking", category: "food and recipe" },
	{
		label: "Cooking Techniques",
		value: "cooking-techniques",
		category: "food and recipe",
	},
	{
		label: "Vegan Recipes",
		value: "vegan-recipes",
		category: "food and recipe",
	},

	{
		label: "Productivity",
		value: "productivity",
		category: "personal development",
	},
	{
		label: "Self-Improvement",
		value: "self-improvement",
		category: "personal development",
	},
	{
		label: "Mindfulness",
		value: "mindfulness",
		category: "personal development",
	},
	{
		label: "Goal Setting",
		value: "goal-setting",
		category: "personal development",
	},
	{
		label: "Motivation",
		value: "motivation",
		category: "personal development",
	},

	{ label: "Fashion", value: "fashion", category: "lifestyle" },
	{ label: "Fitness", value: "fitness", category: "lifestyle" },
	{ label: "Travel", value: "travel", category: "lifestyle" },
	{ label: "Makeup", value: "makeup", category: "fashion and beauty" },
	{ label: "Skincare", value: "skincare", category: "fashion and beauty" },
	{ label: "Haircare", value: "hairstyle", category: "fashion and beauty" },
	{
		label: "Fashion Trends",
		value: "fashion-trends",
		category: "fashion and beauty",
	},
	{
		label: "Beauty Products",
		value: "beauty-products",
		category: "fashion and beauty",
	},

	{
		label: "Movies",
		value: "movies",
		category: "entertainment",
	},
	{
		label: "TV Shows",
		value: "tv-shows",
		category: "entertainment",
	},
	{
		label: "Music",
		value: "music",
		category: "entertainment",
	},
	{
		label: "Books",
		value: "books",
		category: "entertainment",
	},
	{
		label: "Video Games",
		value: "video-games",
		category: "entertainment",
	},

	{ label: "Team Sports", value: "team-sports", category: "sport" },
	{ label: "Individual Sports", value: "individual-sports", category: "sport" },
	{ label: "Fitness", value: "fitness", category: "sport" },
	{ label: "Outdoor Sports", value: "outdoor-sports", category: "sport" },
	{ label: "Extreme Sports", value: "extreme-sports", category: "sport" },

	{ label: "World News", value: "world-news", category: "politics" },
];
