export const countries = [
	{ name: "Afghanistan", key: "af" },
	{ name: "Albania", key: "al" },
	{ name: "Algeria", key: "dz" },
	{ name: "Andorra", key: "ad" },
	{ name: "Angola", key: "ao" },
	{ name: "Antigua and Barbuda", key: "ag" },
	{ name: "Argentina", key: "ar" },
	{ name: "Armenia", key: "am" },
	{ name: "Australia", key: "au" },
	{ name: "Austria", key: "at" },
	{ name: "Azerbaijan", key: "az" },
	{ name: "Bahamas", key: "bs" },
	{ name: "Bahrain", key: "bh" },
	{ name: "Bangladesh", key: "bd" },
	{ name: "Barbados", key: "bb" },
	{ name: "Belarus", key: "by" },
	{ name: "Belgium", key: "be" },
	{ name: "Belize", key: "bz" },
	{ name: "Benin", key: "bj" },
	{ name: "Bhutan", key: "bt" },
	{ name: "Bolivia", key: "bo" },
	{ name: "Bosnia and Herzegovina", key: "ba" },
	{ name: "Botswana", key: "bw" },
	{ name: "Brazil", key: "br" },
	{ name: "Brunei Darussalam", key: "bn" },
	{ name: "Bulgaria", key: "bg" },
	{ name: "Burkina Faso", key: "bf" },
	{ name: "Burundi", key: "bi" },
	{ name: "Cabo Verde", key: "cv" },
	{ name: "Cambodia", key: "kh" },
	{ name: "Cameroon", key: "cm" },
	{ name: "Canada", key: "ca" },
	{ name: "Central African Republic", key: "cf" },
	{ name: "Chad", key: "td" },
	{ name: "Chile", key: "cl" },
	{ name: "China", key: "cn" },
	{ name: "Colombia", key: "co" },
	{ name: "Comoros", key: "km" },
	{ name: "Congo (Congo-Brazzaville)", key: "cg" },
	{ name: "Costa Rica", key: "cr" },
	{ name: "Croatia", key: "hr" },
	{ name: "Cuba", key: "cu" },
	{ name: "Cyprus", key: "cy" },
	{ name: "Czech Republic", key: "cz" },
	{ name: "Democratic Republic of the Congo", key: "cd" },
	{ name: "Denmark", key: "dk" },
	{ name: "Djibouti", key: "dj" },
	{ name: "Dominica", key: "dm" },
	{ name: "Dominican Republic", key: "do" },
	{ name: "Ecuador", key: "ec" },
	{ name: "Egypt", key: "eg" },
	{ name: "El Salvador", key: "sv" },
	{ name: "Equatorial Guinea", key: "gq" },
	{ name: "Eritrea", key: "er" },
	{ name: "Estonia", key: "ee" },
	{ name: "Eswatini", key: "sz" },
	{ name: "Ethiopia", key: "et" },
	{ name: "Fiji", key: "fj" },
	{ name: "Finland", key: "fi" },
	{ name: "France", key: "fr" },
	{ name: "Gabon", key: "ga" },
	{ name: "Gambia", key: "gm" },
	{ name: "Georgia", key: "ge" },
	{ name: "Germany", key: "de" },
	{ name: "Ghana", key: "gh" },
	{ name: "Greece", key: "gr" },
	{ name: "Grenada", key: "gd" },
	{ name: "Guatemala", key: "gt" },
	{ name: "Guinea", key: "gn" },
	{ name: "Guinea-Bissau", key: "gw" },
	{ name: "Guyana", key: "gy" },
	{ name: "Haiti", key: "ht" },
	{ name: "Honduras", key: "hn" },
	{ name: "Hungary", key: "hu" },
	{ name: "Iceland", key: "is" },
	{ name: "India", key: "in" },
	{ name: "Indonesia", key: "id" },
	{ name: "Iran", key: "ir" },
	{ name: "Iraq", key: "iq" },
	{ name: "Ireland", key: "ie" },
	{ name: "Israel", key: "il" },
	{ name: "Italy", key: "it" },
	{ name: "Jamaica", key: "jm" },
	{ name: "Japan", key: "jp" },
	{ name: "Jordan", key: "jo" },
	{ name: "Kazakhstan", key: "kz" },
	{ name: "Kenya", key: "ke" },
	{ name: "Kiribati", key: "ki" },
	{ name: "Korea, Democratic People's Republic of (North Korea)", key: "kp" },
	{ name: "Korea, Republic of (South Korea)", key: "kr" },
	{ name: "Kuwait", key: "kw" },
	{ name: "Kyrgyzstan", key: "kg" },
	{ name: "Lao PDR (Laos)", key: "la" },
	{ name: "Latvia", key: "lv" },
	{ name: "Lebanon", key: "lb" },
	{ name: "Lesotho", key: "ls" },
	{ name: "Liberia", key: "lr" },
	{ name: "Libya", key: "ly" },
	{ name: "Liechtenstein", key: "li" },
	{ name: "Lithuania", key: "lt" },
	{ name: "Luxembourg", key: "lu" },
	{ name: "Madagascar", key: "mg" },
	{ name: "Malawi", key: "mw" },
	{ name: "Malaysia", key: "my" },
	{ name: "Maldives", key: "mv" },
	{ name: "Mali", key: "ml" },
	{ name: "Malta", key: "mt" },
	{ name: "Marshall Islands", key: "mh" },
	{ name: "Mauritania", key: "mr" },
	{ name: "Mauritius", key: "mu" },
	{ name: "Mexico", key: "mx" },
	{ name: "Micronesia", key: "fm" },
	{ name: "Moldova", key: "md" },
	{ name: "Monaco", key: "mc" },
	{ name: "Mongolia", key: "mn" },
	{ name: "Montenegro", key: "me" },
	{ name: "Morocco", key: "ma" },
	{ name: "Mozambique", key: "mz" },
	{ name: "Myanmar", key: "mm" },
	{ name: "Namibia", key: "na" },
	{ name: "Nauru", key: "nr" },
	{ name: "Nepal", key: "np" },
	{ name: "Netherlands", key: "nl" },
	{ name: "New Zealand", key: "nz" },
	{ name: "Nicaragua", key: "ni" },
	{ name: "Niger", key: "ne" },
	{ name: "Nigeria", key: "ng"},
	{ name: "North Macedonia", key: "mk" },
	{ name: "Norway", key: "no" },
	{ name: "Oman", key: "om" },
	{ name: "Pakistan", key: "pk" },
	{ name: "Palau", key: "pw" },
	{ name: "Palestine", key: "ps" },
	{ name: "Panama", key: "pa" },
	{ name: "Papua New Guinea", key: "pg" },
	{ name: "Paraguay", key: "py" },
	{ name: "Peru", key: "pe" },
	{ name: "Philippines", key: "ph" },
	{ name: "Poland", key: "pl" },
	{ name: "Portugal", key: "pt" },
	{ name: "Qatar", key: "qa" },
	{ name: "Romania", key: "ro" },
	{ name: "Russia", key: "ru" },
	{ name: "Rwanda", key: "rw" },
	{ name: "Saint Kitts and Nevis", key: "kn" },
	{ name: "Saint Lucia", key: "lc" },
	{ name: "Saint Vincent and the Grenadines", key: "vc" },
	{ name: "Samoa", key: "ws" },
	{ name: "San Marino", key: "sm" },
	{ name: "Sao Tome and Principe", key: "st" },
	{ name: "Saudi Arabia", key: "sa" },
	{ name: "Senegal", key: "sn" },
	{ name: "Serbia", key: "rs" },
	{ name: "Seychelles", key: "sc" },
	{ name: "Sierra Leone", key: "sl" },
	{ name: "Singapore", key: "sg" },
	{ name: "Slovakia", key: "sk" },
	{ name: "Slovenia", key: "si" },
	{ name: "Solomon Islands", key: "sb" },
	{ name: "Somalia", key: "so" },
	{ name: "South Africa", key: "za" },
	{ name: "South Sudan", key: "ss" },
	{ name: "Spain", key: "es" },
	{ name: "Sri Lanka", key: "lk" },
	{ name: "Sudan", key: "sd" },
	{ name: "Suriname", key: "sr" },
	{ name: "Sweden", key: "se" },
	{ name: "Switzerland", key: "ch" },
	{ name: "Syria", key: "sy" },
	{ name: "Taiwan", key: "tw" },
	{ name: "Tajikistan", key: "tj" },
	{ name: "Tanzania", key: "tz" },
	{ name: "Thailand", key: "th" },
	{ name: "Timor-Leste", key: "tl" },
	{ name: "Togo", key: "tg" },
	{ name: "Tonga", key: "to" },
	{ name: "Trinidad and Tobago", key: "tt" },
	{ name: "Tunisia", key: "tn" },
	{ name: "Turkey", key: "tr" },
	{ name: "Turkmenistan", key: "tm" },
	{ name: "Tuvalu", key: "tv" },
	{ name: "Uganda", key: "ug" },
	{ name: "Ukraine", key: "ua" },
	{ name: "United Arab Emirates", key: "ae" },
	{ name: "United Kingdom", key: "gb" },
	{ name: "United States of America", key: "us" },
	{ name: "Uruguay", key: "uy" },
	{ name: "Uzbekistan", key: "uz" },
	{ name: "Vanuatu", key: "vu" },
	{ name: "Vatican City (Holy See)", key: "va" },
	{ name: "Venezuela", key: "ve" },
	{ name: "Viet Nam", key: "vn" },
	{ name: "Yemen", key: "ye" },
	{ name: "Zambia", key: "zm" },
	{ name: "Zimbabwe", key: "zw" },
];
